### ISSUE TITLE
Multiple Datatables in the same view and from the same model!

### ISSUE THREAD

**Issue by salouri** [tigrang/cakephp-datatable#53]
I have two data sets (datatables) in the same view, they both fetch data from the same model. Normally I could just have the same settings in the related action and do the filtering on aoColumns on the front side. However, one data set is filtered based on data from another model, while the other isn't.

Any ideas??

**Comment by tigrang** [comment]
@salouri Hey, this is really late I know. But you can try out the dev branch which has what you were looking for. Documentation at: https://gist.github.com/tigrang/755d77500c97ae3e5953 It's still a WIP.

**Comment by tigrang** [comment]
Latest docs in the wiki https://github.com/tigrang/cakephp-datatable/wiki/ Its for the dev branch.

**Comment by tigrang** [comment]
This has been merged into master. Check the wiki for docs. Thanks.
