### ISSUE TITLE
extra view processing not working

### ISSUE THREAD

**Issue by mplabs** [tigrang/cakephp-datatable#57]
I'm trying to get the extra view processing to work. I disabled autoRender and created a /app/View/[Model]/datatable/[config_name].ctp file.
This file is not processed, all I get is an empty response. What am I doing wrong?

**Comment by mplabs** [comment]
The problem was that I set _serialize in my AppController. This will cause JsonView::render to not render the datatable view file.

**Comment by tigrang** [comment]
Can you paste the relevant code? Thanks.

**Comment by mplabs** [comment]
In my AppController:beforeFilter() function I had
`$this->set('_serialize', array('user'));`

Now in [CORE]/Cake/View/JsonView.php:103-109 you have
```
public function render($view = null, $layout = null) {
  $return = null;
  if (isset($this->viewVars['_serialize'])) {
    $return = $this->_serialize($this->viewVars['_serialize']);
  } elseif ($view !== false && $this->_getViewFileName($view)) {
    $return = parent::render($view, false);
  }
[...]
```
Because of that, if you have set the `_serialize` view variable, the JsonView will not render any template you might have in `[APP]/View/{model}/datatable/{config}.ctp` but will instead just dump your variables, hence you have no view processing.

I don't know if that is actually a bug or if it should just be stated in the docs as an edge-case.

**Comment by tigrang** [comment]
If you set `autoRender` to false it wouldn't be using JsonView. Paste your component configuration.

**Comment by tigrang** [comment]
You are right. Let me look into this.

**Comment by tigrang** [comment]
Why do you have a `_serialize` in `AppController::beforeFilter()` though?

**Comment by mplabs** [comment]
I have a javascript application running in the background that will fetch certain pages or just data. A lot of the time, I need the logged in user for these requests. That's why I was setting it. I am now changing it to just hav the _serialize set when I really need it.

**Comment by tigrang** [comment]
Fixing it is pretty trivial, but I feel like _serialize shouldn't be set in the first place. I'm going to close this issue.

Thanks for trying out the new version btw :) Any other issues or things you wish were different?
