### ISSUE TITLE
Localisation of column names

### ISSUE THREAD

**Issue by polak25** [tigrang/cakephp-datatable#58]
Hello,

i have a problem if i want to traduce the column names with __() in my controller settings

    public $components = [
		'DataTable.DataTable' => [
			'Badge' => [
				'columns' => [
					'id' => 'Réf',
					'num_serigraphe' => 'Numéro de sérigraphie',
					'num_serie' => 'Numéro de sérigraphie',
					'status' => 'Status',
					'created' => 'Créé le',
					'modified' => 'Modifié le',
					'' => null,
				],
				'autoData' => false,
				//'autoRender' => false
			],
		],
	];

**Comment by tigrang** [comment]
You can set it up in `beforeFilter()` method:

```php
public function beforeFilter() {
    parent::beforeFilter();
    $this->DataTable->settings['Badge']['columns'] = [
        'id' => __('Id'),
        // ...
    ];
}
```

**Comment by polak25** [comment]
it works perfectly, thank you!
