### ISSUE TITLE
Have a $_GET conditions

### ISSUE THREAD

**Issue by polak25** [tigrang/cakephp-datatable#59]
Hello,

i have no solution to send $this->params to a condition ?

    public function beforeFilter() {
		parent::beforeFilter();

		$this->DataTable->settings[$this->modelClass]['conditions'] = array(
			$this->modelClass.'.client_id' => $this->Auth->user('client_id'),
			$this->modelClass.'.status' => ??
		);

**Comment by tigrang** [comment]
`$this->request->query('name_of_field')`
