### ISSUE TITLE
Link to "Component Configuration" in wiki incorrect

### ISSUE THREAD

**Issue by fr0z3nfyr** [tigrang/cakephp-datatable#63]
Not really an issue, but didn't know where else to post so that new visitors also have get a view of the URL if not fixed. Sorry, if this shouldn't be listed in issues. 

Right now, the "Component Configuration" link points to http://link1.com/ instead of https://github.com/tigrang/cakephp-datatable/wiki/Component-Configuration Please fix the link on [this wiki page - instruction#3] (https://github.com/tigrang/cakephp-datatable/wiki/Getting-Started).

Thanks for the great plugin, looks promising. I've just started testing it in one of my projects, will come back if I get into any troubles.

**Comment by tigrang** [comment]
Hey @fr0z3nfyr,

Thanks for letting me know. The link has been fixed.
